[[resource-temporalProperty-section]]
=== Resource TemporalProperty
==== Overview
The `TemporalProperty` resource supports retrieving and creating operations via GET and POST HTTP methods respectively.

. Retrieving operation returns a `TemporalProperty` resource which is included in the <<resource-tproperties-collection-section,`TemporalPropertyCollection`>> that specified by <<tproperties-identifier,{tPropertyName}>>. The `TemporalProperty` resource returned to the response can be limited using the <<limit-section,`limit`>>, <<datetime-section,`datetime`>>, and <<leaf-section,`leaf`>> parameters.
. Creating operation post a new temporal value object to the <<resource-tproperties-collection-section,`TemporalPropertyCollection`>> that specified by <<tproperties-identifier,{tPropertyName}>>.

[[temporal-properties-object]]
A temporal property object is a collection of dynamic non-spatial attributes and their temporal values with time.
An abbreviated copy of this information is returned for each `TemporalProperty` in the `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` response.

The schema for the temporal property object presented in this clause is an extension of the `TemporalProperty Object` defined in link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#tproperties[MF-JSON standard].
<<temporalProperty-properties-table>> defines the set of property that may be used to describe a temporal property.

[[temporalProperty-properties-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of the properties related to the temporal property
[cols="20,15,65",options="header"]
|===
|Property           |Requirement    |Description
|name               |M |An identifier for the resource assigned by an external entity.
|type               |M |A predefined temporal property type (i.e., one of 'TBoolean', 'TText', 'TInteger', 'TReal', and 'TImage').
|values             |O |A sequence of <<temporalValue-properties-table, temporal value>>
|form               |O |A unit of measure.
|description        |O |A short description.
|===

[[temporalValue-properties-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of the properties related to the temporal value
[cols="20,15,65",options="header"]
|===
|Property           |Requirement    |Description
|datetimes          |M |A sequence of monotonic increasing instants.
|values             |M |A sequence of dynamic value, having the same number of elements as "datetimes".
|interpolation      |M |A predefined type for a dynamic value (i.e., one of 'Discrete', 'Step', 'Linear', or 'Regression').
|===

NOTE: The detailed information and requirements for each property are described in the <<OGC-MF-JSON, OGC Moving Feature JSON encoding standard>>.

include::requirements/movingfeature/tproperties/REQ_mandatory-tproperties.adoc[]

==== Operation
===== Retrieve
. Issue a `GET` request on the `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` path

[[tproperties-identifier]]
The `{tPropertyName}` parameter is the unique identifier for a single temporal property value offered by the API.
The list of valid values for `{tPropertyName}` is provided in the <<resource-tproperties-collection-section,`{root}/collections/{collectionId}/items/{mFeatureId}/tproperties`>> GET response.

include::requirements/movingfeature/tproperties/REQ_operation-tproperties-get.adoc[]

====== Create
This operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#create[CREATE]` conformance class of API-Features.
This operation targeted <<temporalValue-properties-table,TemporalValue>> object.

. Issue a `POST` request on `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` path

Support for HTTP POST method is required by API-Features.

include::requirements/movingfeature/tproperties/REQ_operation-tproperties-post.adoc[]

[#tvalue-schema,reftext='TemporalValue Schema']
.TemporalProperty Request Body Schema (temporalValue.yaml)
[source,yaml]
----
include::../openapi/schemas/temporalValue.yaml[]
----

The following example adds a new feature (<<temporalValue-properties-table, TemporalValue>> object) to the feature created by the <<tproperties-post-example,Creation a New TemporalProperty Object Example>>.
The feature is represented as JSON.
A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.
[#temporalvalue-post-example,reftext='Create a New TemporalValue Object Example']
.Create a New TemporalValue Object Example
include::examples/temporalValue-post.adoc[]

==== Response
===== Retrieve
A successful response to the `TemporalProperty` GET operation is a temporal property identified by the <<tproperties-identifier,`{tPropertyName}`>> parameter.

include::requirements/movingfeature/tproperties/REQ_response-tproperties-get.adoc[]

The following JSON payload is an example of a response to an OGC API Moving Features `TemporalProperty` GET operation.
[#tproperties-example,reftext=`TemporalProperty GET Example`]
.TemporalProperty GET Example
[source,json]
----
include::../openapi/examples/temporalValueCollection.json[]
----

====== Create
A successful response to the `TemporalProperty` POST operation is an HTTP status code.

include::requirements/movingfeature/tproperties/REQ_response-tproperties-post.adoc[]

==== Error situations
The requirements for handling unsuccessful requests are provided in <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.