[[resource-temporalProperty-section]]
=== Resource TemporalProperty
==== Overview
The *TemporalProperty* resource supports the retrieve and create operations via the HTTP GET and POST methods respectively.

. A retrieve operation returns a *TemporalProperty* resource which is included in the <<resource-temporalProperties-section,*TemporalProperties*>> that specified by <<tproperty-identifier,{tPropertyName}>>.
The *TemporalProperty* resource returned to the response can be limited using the parameters <<datetime-section,`datetime`>>, <<leaf-section,`leaf`>> and <<subTemporalValue-section,`subTemporalValue`>>.
. A create operation posts a new temporal primitive value object to the <<resource-temporalProperties-section,*TemporalProperties*>> that specified by <<tproperty-identifier,{tPropertyName}>>.

[[temporal-properties-object]]
A temporal property object is a collection of dynamic non-spatial attributes and their temporal values with time.
An abbreviated copy of this information is returned for each *TemporalProperty* in the `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` response.

The schema for the temporal property object presented in this clause is an extension of the link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#tproperties[*_ParametricValues_* Object] defined in <<OGC_19-045r3,MF-JSON>>.
<<temporalProperty-properties-table>> defines the set of property that may be used to describe a temporal property.

[[temporalProperty-properties-table]]
.Table of the properties related to the temporal property
[cols="20,15,65",options="header"]
|===
|Property           |Requirement    |Description
|*_name_*               |M |An identifier for the resource assigned by an external entity.
|*_type_*               |M |A predefined temporal property type (i.e., one of 'TBoolean', 'TText', 'TInteger', 'TReal', and 'TImage').
|*_valueSequence_*      |M |A sequence of <<temporalValue-properties-table, temporal primitive value>>
|*_form_*               |O |A unit of measure.
|*_description_*        |O |A short description.
|===

[[temporalValue-properties-table]]
.Table of the properties related to the temporal primitive value
[cols="20,15,65",options="header"]
|===
|Property           |Requirement    |Description
|*_datetimes_*          |M |A sequence of monotonic increasing instants.
|*_values_*             |M |A sequence of dynamic values having the same number of elements as "datetimes".
|*_interpolation_*      |M |A predefined type for a dynamic value (i.e., one of 'Discrete', 'Step', 'Linear', or 'Regression').
|===

NOTE: The detailed information and requirements for each property are described in the <<OGC_19-045r3,OGC Moving Feature JSON Encoding Standard>>.

include::requirements/movingfeature/tproperty/REQ_mandatory-tproperty.adoc[]

==== Query Parameters
Query parameters are used in URLs to define the resources which are returned on a GET request.

The query parameter link:http://docs.opengeospatial.org/DRAFTS/20-024.html#datetime-parameter-requirements[`datetime`] is inherited from OGC API — Common.

The <<leaf-section,`leaf`>> query parameter is defined in the <<resource-temporalGeometrySequence-section,*TemporalGeometrySequence*>> clause.

The <<subTemporalValue-section,`subTemporalValue`>> query parameter is defined in the <<resource-temporalProperties-section,*TemporalProperties*>> clause.

==== Operation
===== Retrieve
. Issue a `GET` request on the `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` path

[[tproperty-identifier]]
The `{tPropertyName}` parameter is the unique identifier for a single temporal property value offered by an implementation instance (endpoint) of the OGC API — MF.
The list of valid values for `{tPropertyName}` is provided in the <<resource-temporalProperties-section,`{root}/collections/{collectionId}/items/{mFeatureId}/tproperties`>> GET response.

include::requirements/movingfeature/tproperty/REQ_operation-tproperty-get.adoc[]

====== Create
The create operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#create[CREATE]` conformance class in the OGC API — Features.
This operation targeted the new temporal primitive value object defined in <<temporalValue-properties-table>>.

. Issue a `POST` request on `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` path

Support for the HTTP POST method is specified as a requirement in OGC API — Features.

include::requirements/movingfeature/tproperty/REQ_operation-tproperty-post.adoc[]

[[tvalue-schema]]
.TemporalProperty Request Body Schema (TemporalPrimitiveValue.yaml):
[source,yaml]
----
include::../openapi/schemas/temporalPrimitiveValue.yaml[]
----

The following example adds a new feature (<<temporalValue-properties-table,TemporalPrimitiveValue>> object) to the feature created by <<tproperties-post-example,Creating a New TemporalPrimitiveValue Object Example>>.
The feature is represented as a JSON payload.
A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

[[temporalvalue-post-example]]
.An Example of Creating a New TemporalPrimitiveValue Object:
include::examples/temporalValue-post.adoc[]

===== Delete
The delete operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#delete[DELETE]` conformance class of API — Features.

. Issue a `DELETE` request on `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` path

Support for the HTTP DELETE method is specified as a requirement in OGC API — Features.

include::requirements/movingfeature/tproperty/REQ_operation-tproperty-delete.adoc[]

==== Response
===== Retrieve
A successful response to the *TemporalProperty* GET operation is a temporal property identified by the <<tproperty-identifier,`{tPropertyName}`>> parameter.

include::requirements/movingfeature/tproperty/REQ_response-tproperty-get.adoc[]

The following JSON payload is an example of a response to an OGC API — Moving Features *TemporalProperty* GET operation.

[[tproperties-valuesequence-example]]
.An Example of *TemporalProperty* GET Operation:
[source,json]
----
include::../openapi/examples/temporalPrimitiveValueSequence.json[]
----

====== Create
A successful response to the *TemporalProperty* POST operation is an HTTP status code.

include::requirements/movingfeature/tproperty/REQ_response-tproperty-post.adoc[]

===== Delete
A successful response to the *TemporalProperty* DELETE operation is an HTTP status code.

include::requirements/movingfeature/tproperty/REQ_response-tproperty-delete.adoc[]

==== Error situations
The requirements for handling unsuccessful requests are provided in the <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.