== Introduction
[big]*i.     Abstract*

<Insert Abstract Text here>

[big]*ii.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document, OGC MovingFeature, MovingFeatures JSON, MovingFeature Access, API, OpenAPI, REST, trajectory

[big]*iii.   Preface*

[NOTE]
====
Insert Preface Text here. Give OGC specific commentary: describe the technical content, reason for document, history of the document and precursors, and plans for future work. >

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights.
The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims
or other intellectual property rights of which they may be aware that might be infringed by any implementation of
the standard set forth in this document, and to provide supporting documentation.
====
[big]*iv.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

* Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology

* Université libre de Bruxelles

* Geomatys

[big]*v.     Submitters*

All questions regarding this submission should be directed to the editor or the submitters:

{set:cellbgcolor!}
[width="99%", cols="3,7"]
|===========================================================
|*Name*                 |*Organization*
|Kyoung-Sook KIM        |Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
|Taehoon KIM            |Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
|Mahmoud SAKR           |Université libre de Bruxelles
|Martin Desruisseaux    |Geomatys
|===========================================================
