.Preface

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

Moving feature data can represent various phenomena, including vehicles, people, animals, weather patterns, etc.
The OGC API - Moving Features (OGC API — Moving Features) Standard defines a standard interface for querying and accessing geospatial data that changes over time, such as the location and attributes of moving objects like vehicles, vessels, or pedestrians.
The API specified in this Standard provides a way to manage data representing moving features, which can be helpful for applications in domains such as transportation management, disaster response, and environmental monitoring. This Standard also specifies operations for filtering, sorting, and aggregating moving feature data based on location, time, and other properties. The OGC API - Moving Features - Part 1: Core Standard specifies a set of RESTful interfaces and data formats for querying and updating moving feature data over the web. The Standard is part of the OGC API family of Standards and makes use of the OpenAPI Specification.
<<OGC-API,OGC API Standards>> define modular API building blocks that spatially enable Web APIs in a consistent way.
<<OPENAPI,OpenAPI>> is used to define the reusable API building blocks with responses in JSON and HTML.

The OGC API family of standards is organized by resource type.

[[common-paths]]
.Overview of Resources
[width="99%",cols=",,,",options="header"]
|====
| Resource | Path | HTTP Method | Document Reference
// | Landing page                  | ``/``                           | GET | <<common-landingpage-section, 7.2 API Landing Page>>
// | API definition                 | ``/api``                        | GET | <<common-api-section, 7.3 API Definition>>
// | Conformance classes           | ``/conformance``                | GET | <<common-conformance-section, 7.4 Declaration of Conformance Classes>>
| Collections metadata          | ``/collections``                | GET, POST | <<resource-collections-section,Resource Collections>>
| Collection instance metadata  | ``/collections/{collectionId}`` | GET, DELETE, PUT | <<resource-collection-section,Resource Collection>>
| MovingFeatures                | ``/collections/{collectionId}/items`` | GET, POST | <<resource-movingfeatures-section,Resource MovingFeatures>>
| MovingFeature instance        | ``/collections/{collectionId}/items/{mFeatureId}`` | GET, DELETE | <<resource-movingfeature-section,Resource MovingFeature>>
| TemporalGeometrySequence      | ``/collections/{collectionId}/items/{mFeatureId}/tgsequence`` | GET, POST | <<resource-temporalGeometrySequence-section,Resource TemporalGeometrySequence>>
| TemporalPrimitiveGeometry instance     | ``/collections/{collectionId}/items/{mFeatureId}/tgsequence/{tGeometryId}`` | DELETE | <<resource-temporalPrimitiveGeometry-section,Resource TemporalPrimitiveGeometry>>
| Queries for TemporalPrimitiveGeometry  | ``collections/{collectionId}/items/{mFeatureId}/tgsequence/{tGeometryId}/{queryType}`` | GET | <<resource-tgsequenceQuery-section,TemporalGeometry Query Resources>>
| TemporalProperties   | ``/collections/{collectionId}/items/{mFeatureId}/tproperties`` | GET, POST | <<resource-temporalProperties-section,Resource TemporalProperties>>
| TemporalProperty instance     | ``/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyId}`` | GET, POST, DELETE | <<resource-temporalProperty-section,Resource TemporalProperty>>
| TemporalPrimitiveValue instance     | ``/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyId}/{tValueId}`` | DELETE | <<resource-temporalPrimitiveValue-section,Resource TemporalProperty>>
|====


== Security considerations

The OGC API - Moving Features - Part 1: Core Standard does not mandate any specific security controls.
However, it was designed to support addition of security controls without impacting conformance, in a similar way to the link:https://docs.ogc.org/is/19-072/19-072.html#_91afaabd-dc29-41eb-805d-15e1afd18825[OGC API — Common — Part 1: Core Standard].

This document therefore applies Requirement link:https://docs.ogc.org/is/19-072/19-072.html#rc_oas30-security[/req/oas30/security] of OGC API - Common - Part 1: Core for OpenAPI 3.0 support of security controls.


== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[[tbl_submitters]]
[width="99%", cols="3,7",options="header"]
|===========================================================
|*Name*                 |*Organization*
|Taehoon KIM            |Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
|Kyoung-Sook KIM        |Artificial Intelligence Research Center, National Institute of Advanced Industrial Science and Technology
|Mahmoud SAKR           |Université libre de Bruxelles
|Esteban Zimanyi        |Université libre de Bruxelles
|Martin Desruisseaux    |Geomatys
|Akinori Asahara        |Central Research Laboratory, Hitachi Ltd.
|Chen-Yu Hao            |Feng Chia University
|===========================================================
