== Conformance
This Standard defines multiple requirements classes and conformance classes that describe different levels of conformance to the Standard.
These requirements / conformance classes help to ensure interoperability between separate implementations of the Standard and enable data providers to specify which parts of the Standard they support.
The standardization targets are "Web APIs".

The conformance classes specified in this Standard are:

* <<clause-core-collection, Collection Catalog>>
* <<clause-core-movingfeature, Moving Features>>
* <<clause-common-req, Common Requirements>>

The conformance class defines the minimum requirements for an API to be compliant with the OGC API - Moving Features Standard.
This includes support for querying and retrieving information about moving features using HTTP GET requests.
Also, the conformance class enables clients to add, modify, or delete features from the server using HTTP POST, PUT, and DELETE requests.
Lastly, the conformance class adds support for querying and retrieving features based on their temporal characteristics, such as their position at a specific time or their velocity over a given time interval.

Implementers of the OGC API - Moving Features can choose which conformance classes they want to support based on the specific needs of their use case and the capabilities of their software. However, to be considered compliant with the Standard, an implementation shall support all the conformance classes listed in <<conf_class_uris>>.

The URIs of the associated conformance classes are:

[[conf_class_uris]]
.Conformance class URIs
[cols="25,75",options="header"]
|===
|Conformance class  |URI
|MovingFeatures Collection Catalog |http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/mf-collection
|MovingFeatures     |http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/movingfeatures
|Common Requirements|http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/common
|===

Conformance with this Standard shall be checked using all the relevant tests specified in <<clause-ATS, Annex A>> of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the
link:https://docs.ogc.org/pol/08-134r11.html[OGC Compliance Testing Policies and Procedures] and the link:https://cite.ogc.org/teamengine/[OGC Compliance Testing website]. The schemas and example API definition documents specified in this Standard can be found in the https://schemas.opengis.net/ogcapi/movingfeatures/part1/1.0/[OGC Schema Repository].
