[[resource-collections-section]]
=== Resource Collections
The `Collections` resource supports retrieving and creating operations via GET and POST HTTP methods respectively.

. Retrieving operation returns a set of metadata which describes the collections available from this API. The catalog of collections returned to the response can be limited using the <<limit-section,`limit`>>, <<bbox-section,`bbox`>>, and <<datetime-section,`datetime`>> parameters.
. Creating operation posts a new <<resource-collection-section,Collection>> resource instance to the collections with this API.

==== Operations
===== Retrieve
This operation is defined in the `link:https://docs.ogc.org/DRAFTS/20-024.html#rc-collections-section[Collections]` conformance class of API-Common.
No modifications are needed to support `MovingFeature` resources.

. Issue a `GET` request on `{root}/collections` path

Support for HTTP GET method on the `{root}/collections` path is required by API-Common.

include::requirements/collection_catalog/collections/REQ_operation-collections-get.adoc[]

====== Create
This operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#create[CREATE]` conformance class of API-Features.
This operation targeted <<resource-collection-section,Collection>> resource.

. Issue a `POST` request on `{root}/collections` path

Support for HTTP POST method is required by API-Features.

include::requirements/collection_catalog/collections/REQ_operation-collections-post.adoc[]

[#collection-requestbody-schema,reftext='Collection Request Body Schema']
.Collection Request Body Schema
[source,yaml]
----
include::../openapi/schemas/requestBody/collection.yaml[]
----

The following example adds a new feature (collection information) to the feature collections.
The feature is represented as JSON.
A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.
[#collections-post-example,reftext='Create a New Collection Example']
.Create a New Collection Example
include::examples/collection-post.adoc[]

==== Response
===== Retrieve
A successful response to the `Collections` GET operation is a document that contains summary metadata for each collection accessible through the API.
In a typical API deployment, the `Collections` GET response will list collections of all offered resource types.
The collections where the value of the `itemType` property is `movingfeature` are collections of moving features.

include::requirements/collection_catalog/collections/REQ_response-collections-get.adoc[]

[#collections-schema,reftext='Collections GET Response Schema']
.Collections GET Response Schema (collections.yaml)
[source,yaml]
----
include::../openapi/schemas/collections.yaml[]
----


The following JSON payload is an example of a response to an OGC API-Moving Features `Collections` GET operation.
[#collections-example,reftext=`Collections Example`]
.Collections Example
[source,json]
----
include::../openapi/examples/collections.json[]
----

====== Create
A successful response to the `Collections` POST operation is an HTTP status code.

include::requirements/collection_catalog/collections/REQ_response-collections-post.adoc[]

==== Error situations
The requirements for handling unsuccessful requests are provided in <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.