[[resource-temporalGeometry-section]]
=== Resource TemporalGeometry

[[temporal-geometry-object]]
A temporal geometry object represents the movement of a moving feature with various types of moving geometry, i.e., `MovingPoint`, `MovingLineString`, `MovingPolygon`, and `MovingPointCloud`. It can also represent the movement of a 3D object with its orientation.

The schema for the temporal geometry object presented in this clause is an extension of the `TemporalGeometry Object` defined in link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#tgeometry[MF-JSON standard].
<<temporalGeometry-properties-table>> defines the set of properties that may be used to describe a temporal geometry.

[[temporalGeometry-properties-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of the properties related to the temporal geometry
[cols="20,15,65",options="header"]
|===
|Property           |Requirement    |Description
|id                 |O |An identifier for the resource assigned by an external entity.
|type               |M |A primitive geometry type of MF-JSON (i.e., one of 'MovingPoint', 'MovingLineString', 'MovingPolygon', 'MovingPointCloud', or 'MovingGeometryCollection').
|datetimes          |M |A sequence of monotonic increasing instants.
|coordinates        |M |A sequence of leaf geometries of a temporal geometry, having the same number of elements as "datetimes".
|interpolation      |M |A predefined type of motion curve (i.e., one of 'Discrete', 'Step', 'Linear', 'Quadratic' or 'Cubic').
|base.type          |O |A type of 3D file format, such as 'STL', 'OBJ', 'PLY', and 'glTF'.
|base.href          |O |A URL to address a 3D model data which represents a base geometry of a 3D shape.
|orientations.scales|O |An array value of numbers along the x, y, and z axis in order as three scale factors.
|orientations.angles|O |An array value of numbers along the x, y, and z axis in order as Euler angles in degree.
|===

NOTE: The detailed information and requirements for each property are described in the <<OGC-MF-JSON, OGC Moving Feature JSON encoding standard>>.

include::requirements/movingfeature/tgeometries/REQ_mandatory-temporalgeometry.adoc[]

==== Operation
===== Delete
This operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#delete[DELETE]` conformance class of API-Features.

. Issue a `DELETE` request on `{root}/collections/{collectionId}/items/{mFeatureId}/tgeometries/{tGeometryId}` path

[[tgeometry-identifier]]
The {tGeometryId} parameter is the unique identifier for a single temporal geometry offered by the API.
The list of valid values for `{tGeometryId}` is provided in the <<resource-tgeometries-section,`{root}/collections/{collectionId}/items/{mFeatureId}/tgeometries`>> GET response.

Support for HTTP DELETE method is required by API-Features.

include::requirements/movingfeature/tgeometry/REQ_operation-tgeometry-delete.adoc[]

==== Response
===== Delete
A successful response to the `TemporalGeometry` DELETE operation is an HTTP status code.

include::requirements/movingfeature/tgeometry/REQ_response-tgeometry-delete.adoc[]

==== Error situations
The requirements for handling unsuccessful requests are provided in <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.