[[resource-collection-section]]
=== Resource Collection
A Collection information object is the set of metadata that describes a single collection.
An abbreviated copy of this information is returned for each `Collection` in the `{root}/collections` GET response.

The schema for the collection information object presented in this clause is an extension of the collection schema defined in link:http://docs.opengeospatial.org/DRAFTS/20-024.html#collection-description[OGC API-Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API-Features].

<<collection-properties-table>> defines the set of properties that may be used to describe a collection.

[#collection-properties-table,reftext='{table-caption} {counter:table-num}']
.Table of collection properties
[cols="25,10,65",options="header"]
|===
|Property           |Requirement |Description
|_**id**_           |M |A unique identifier to the collection.
|_**title**_        |O |A human-readable name given to the collection.
|_**description**_  |O |A free-text description of the collection.
|_**links**_        |M |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.)
|_**extent**_       |O |The spatio-temporal coverage of the collection.
|_**itemType**_     |M |Fixed to the value "movingfeature".
|updateFrequency    |O |A time interval of sampling location. The time unit of this property is millisecond.
|===

NOTE: The _id_, _title_, _description_, _links_, _extent_, and _itemsType_ properties were inherited from link:http://docs.ogc.org/DRAFTS/20-024.html#collections-metadata[OGC API-Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API-Features].

NOTE: An update frequency is one of the most important properties of moving feature collection.
It is determined by a data source. It can be used to determine the continuity of the moving feature's trajectory.

include::requirements/collection_catalog/collection/REQ_mandatory-collection.adoc[]

==== Operation
===== Retrieve
This operation is defined in the `https://docs.ogc.org/DRAFTS/20-024.html#collection-description[Collection]` conformance class of API-Common.
No modifications are required to support `MovingFeature` resources.

. Issue a `GET` request on the `{root}/collections/{collectionId}` path

[[collection-identifier]]
The {collectionId} parameter is the unique identifier for a single collection offered by the API.
The list of valid values for `{collectionId}` is provided in the <<resource-collections-section,`/collections`>> response.

Support for the `{root}/collections/{collectionId}` path is required by OGC API-Common.

include::requirements/collection_catalog/collection/REQ_operation-collection-get.adoc[]

===== Replace
This operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#replace[REPLACE]` conformance class of API-Features.
This operation targeted <<resource-collection-section,Collection>> resource.

. Issue a `PUT` request on `{root}/collections/{collectionId}` path

Support for HTTP PUT method is required by API-Features.

include::requirements/collection_catalog/collection/REQ_operation-collection-put.adoc[]

NOTE: The update frequency cannot be changed once set.

The following example replaces the feature created by the <<collections-post-example, Create Example>> with a new feature (collection information without an update frequency).
Once again, the replacement feature is represented as JSON.
A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.
[#collections-put-example,reftext='Replace an Existing Collection Example']
.Replace an Existing Collection Example
include::examples/collection-put.adoc[]

===== Delete
This operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#delete[DELETE]` conformance class of API-Features.

. Issue a `DELETE` request on `{root}/collections/{collectionId}` path

Support for HTTP DELETE method is required by API-Features.

include::requirements/collection_catalog/collection/REQ_operation-collection-delete.adoc[]

The following example deletes the feature created by the <<collections-post-example, Create Example>> and replaced with a new feature in the <<collections-put-example, Replace Example>>.
A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.
[#collections-delete-example,reftext='Delete an Existing Collection Example']
.Delete an Existing Collection Example
include::examples/collection-delete.adoc[]

==== Response
===== Retrieve
A successful response to the `Collection` GET operation is a set of metadata that describes the collection identified by the <<collection-identifier,`{collectionId}`>> parameter.

include::requirements/collection_catalog/collection/REQ_response-collection-get.adoc[]

[#collection-schema,reftext='Collection GET Response Schema']
.Collection GET Response Schema (collection.yaml)
[source,yaml]
----
include::../openapi/schemas/collection.yaml[]
----

The following JSON payload is an example of a response to an OGC API Moving Features `Collection` GET operation.
[#collection-example,reftext=`Collection Information Example`]
.Collection Information Example
[source,json]
----
include::../openapi/examples/collection.json[]
----

===== Replace
A successful response to the `Collection` PUT operation is an HTTP status code.

include::requirements/collection_catalog/collection/REQ_response-collection-put.adoc[]

===== Delete
A successful response to the `Collection` DELETE operation is an HTTP status code.

include::requirements/collection_catalog/collection/REQ_response-collection-delete.adoc[]

==== Error situations
The requirements for handling unsuccessful requests are provided in <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.