[[resource-temporalProperties-section]]
=== Resource TemporalProperties
==== Overview
A *TemporalProperties* object consists of the set of <<resource-temporalProperty-section,*TemporalProperty*>> which is included in the <<resource-movingfeature-section,*MovingFeature*>> that is specified by <<movingfeature-identifier,{mFeatureId}>>.
The *TemporalProperties* resource supports the retrieve and create operations via the HTTP GET and POST methods respectively.

. A retrieve operation returns a list of the available abbreviated copy of <<resource-temporalProperty-section,*TemporalProperty*>> object in the specified moving feature.
The *TemporalProperties* resource returned to the response can be limited using the query parameters <<limit-section,`limit`>>, <<datetime-section,`datetime`>>, and <<subTemporalValue-section,`subTemporalValue`>>.
. A create operation posts a new <<resource-temporalProperty-section,*TemporalProperty*>> object to the <<resource-movingfeature-section,*MovingFeature*>> that is specified by <<movingfeature-identifier,{mFeatureId}>>.

==== Query Parameters
Query parameters are used in URLs to define the resources which are returned on a GET request.

The query parameters link:http://docs.opengeospatial.org/DRAFTS/20-024.html#datetime-parameter-requirements[`datetime`] and link:http://docs.opengeospatial.org/DRAFTS/20-024.html#limit-parameter-requirements[`limit`] are inherited from OGC API — Common.

[[subTemporalValue-section]]
===== Parameter subTemporalValue
The `subTemporalValue` query parameter is defined as follows:
include::requirements/parameter/REQ_parameter-subtemporalvalue-definition.adoc[]
include::requirements/parameter/REQ_parameter-subtemporalvalue-response.adoc[]

The `subTemporalValue` query parameter is used to select a subset of <<resource-temporalProperty-section,*TemporalProperty*>> for the specified time interval.
Each <<resource-movingfeature-section,*TemporalProperty*>> in the *TemporalProperties* has a sequence of <<resource-temporalPrimitiveValue-section,*TemporalPrimitiveValue*>>.
The `subTemporalValue` parameter behaves functionally the same as the `subTrajectory` parameter.
The difference is that `subTrajectory` is associated with temporal geometry, while `subTemporalValue` is associated with temporal properties.

==== Operation
===== Retrieve
. Issue a `GET` request on the `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` path

include::requirements/movingfeature/tproperties/REQ_operation-tproperties-get.adoc[]

===== Create
The create operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#create[CREATE]` conformance class in the OGC API — Features.
This operation targeted a single or a collection of <<resource-temporalProperty-section,*TemporalProperty*>> resources.

. Issue a `POST` request on `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` path

Support for the HTTP POST method is specified as a requirement in OGC API — Features.

include::requirements/movingfeature/tproperties/REQ_operation-tproperties-post.adoc[]

[[tproperty-schema]]
.TemporalProperties Request Body Schema (temporalProperty.yaml):
[source,yaml]
----
include::../openapi/schemas/temporalProperty.yaml[]
----

// TODO: Add new TemporalProperties request body schema example

The following example adds a new feature (<<temporal-properties-object,*TemporalProperty* Object>> and link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#pvalues[*_ParametricValues_* Object] in <<OGC_19-045r3,MF-JSON>>) to the feature created by the <<movingfeature-post-example,Creation a MovingFeature Example>>.
The feature is represented as a JSON payload.
A pseudo-sequence diagram notation is used to illustrate the details of the HTTP communication between the client and the server.

[[tproperties-post-example]]
.An Example of Creating a New TemporalProperty Object:
include::examples/temporalProperty-post.adoc[]

[[tproperties-post-example2]]
.An Example of Creating a New TemporalProperty Object with *_ParametricValues_* as a MF-JSON encoding:
include::examples/temporalProperty-post-mfjson.adoc[]

==== Response
===== Retrieve
A successful response to the *TemporalProperties* GET operation is a document that contains the set of metadata (and static data) of <<resource-temporalProperty-section,*TemporalProperty*>> in the moving feature identified by the <<movingfeature-identifier,`{mFeatureId}`>> parameter.
The response result does not include dynamic (and temporal information).

If the value of the `subTemporalValue` query parameter is provided, the temporal value of the corresponding `temporalProperties` property of the moving feature is calculated using the `subTemporalValue` parameter value and included in the result.

include::requirements/movingfeature/tproperties/REQ_response-tproperties-get.adoc[]

[[pvalues-schema]]
.TemporalProperties GET Response Schema (TemporalProperties.yaml):
[source,yaml]
----
include::../openapi/schemas/temporalProperties.yaml[]
----

The following JSON payload is an example of a response to an OGC API — Moving Features *TemporalProperties* GET operation.

[[tproperties-example]]
.An Example of a TemporalProperties GET Operation:
[source,json]
----
include::../openapi/examples/temporalPropertyCollection.json[]
----

The following JSON payload is an example of a response to an OGC API — Moving Features *TemporalProperties* GET operation with query parameter `subTemporalValue`.

[[tproperties-example-2]]
.An Example of a TemporalProperties GET Operation with `subTemporalValue`:
[source,json]
----
include::../openapi/examples/temporalProperties.json[]
----

===== Create
A successful response to the *TemporalProperties* POST operation is an HTTP status code.

A link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#pvalues[*_ParametricValues_* Object] in <<OGC_19-045r3,MF-JSON>> can be a collection of <<resource-temporalProperty-section,TemporalProperty>> objects.
Posting a collection of resources is the same as posting a single resource consecutively.
However, because the result must be returned in a single response, the `Locations` header includes a list of the URIs of the newly added resources.
In this case, requirement *B* of link:https://docs.ogc.org/DRAFTS/20-002.html#_response[/req/create-replace-delete/post-response] in OGC API — Features is not applicable.

include::requirements/movingfeature/tproperties/REQ_response-tproperties-post.adoc[]

==== Error situations
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.
