
[[clause-core-collection]]
== Requirements Class "Collection Catalog"
=== Overview
include::requirements/collection_catalog/requirements_class_collection.adoc[]

The `Collection Catalog` requirements class defines the requirements for a collection.
A collection is an object that provides information about and access to a set of related <<clause-core-movingfeature,MovingFeature>>.

=== Information Resources
The two resources defined in this Requirements Class are summarized in <<collection-resources>>.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Catalog Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
.2+|<<resource-collections-section,Collections>>
.2+|`{root}/collections`
^|GET |Get information which describes the set of available Collections
^|POST|Add a new resource (<<resource-collection-section,Collection>>) instance to a Collections

.3+|<<resource-collection-section,Collection>>
.3+|`{root}/collections/
{collectionId}`
^|GET   |Get information about a specific Collection ({collectionId}) of geospatial data with links to distribution
^|PUT   |Update information about a specific Collection ({collectionId})
^|DELETE|Delete a specific Collection ({collectionId})
|===

=== Parameters
The query parameters http://docs.opengeospatial.org/DRAFTS/20-024.html#bbox-parameter-requirements[`bbox`], http://docs.opengeospatial.org/DRAFTS/20-024.html#datetime-parameter-requirements[`datetime`] and http://docs.opengeospatial.org/DRAFTS/20-024.html#limit-parameter-requirements[`limit`] are inherited from API-Common.
All requirements and recommendations in API-Common regarding these parameters also apply for API-Moving Features.

[[limit-section]]
==== Parameter limit
include::requirements/parameter/REQ_parameter-limit.adoc[]

[[bbox-section]]
==== Parameter bbox
include::requirements/parameter/REQ_parameter-bbox.adoc[]

[[datetime-section]]
==== Parameter datetime
include::requirements/parameter/REQ_parameter-datetime.adoc[]

include::clause_8_requirements_resource_collections.adoc[]
include::clause_8_requirements_resource_collection.adoc[]