== Conformance
This standard defines five requirements / conformance classes that describe different levels of compliance with the standard.
These requirements / conformance classes help to ensure interoperability between other implementations of the standard and allow data providers to specify which parts of the standard they support.
The standardization target is "Web APIs".

The conformance classes for OGC API MovingFeatures are:

* <<clause-core-collection, Collection Catalog>>
* <<clause-core-movingfeature, Moving Features>>
// * <<clause-common-req, Common Requirements>>
// * <<clause-mf-json-req, MF-JSON encoding>>
// * <<clause-openapi-req, OpenAPI Specification 3.0>>

The conformance class defines the minimum requirements for an API to be compliant with the OGC API MovingFeatures standard.
This includes support for querying and retrieving information about moving features using HTTP GET requests.
Also, the conformance class enables clients to add, modify, or delete features from the server using HTTP POST, PUT, and DELETE requests.
Lastly, the conformance class adds support for querying and retrieving features based on their temporal characteristics, such as their position at a specific time or their velocity over a given time interval.

Implementers of the OGC API-MF can choose which conformance classes they want to support based on the specific needs of their use case and the capabilities of their software. However, to be considered compliant with the standard, an implementation must support at least the Core conformance class.

The URIs of the associated conformance classes are:

[#conf_class_uris,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="25,75",options="header"]
|===
|Conformance class  |URI
|MovingFeatures Collection Catalog |http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/mf-collection
|MovingFeatures     |http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/movingfeatures
// |Common Requirements|http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/common
// |MF-JSON encoding   |http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/mf-json
// |OpenAPI Specification 3.0 |http://www.opengis.net/spec/ogcapi-movingfeatures-1/1.0/conf/oas31
|===

Conformance with this Standard shall be checked using all the relevant tests specified in <<clause-ATS, Annex A>> of this document.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the
link:https://portal.ogc.org/files/?artifact_id=55234[OGC Compliance Testing Policies and Procedures] and the link:https://cite.opengeospatial.org/teamengine/[OGC Compliance Testing website].
