[[resource-movingfeature-section]]
=== Resource MovingFeature
==== Overview
A *MovingFeature* object consists of the set of static information that describes a single moving feature and the set of temporal object, such as temporal geometry and temporal properties.
An abbreviated copy of this information is returned for each *MovingFeature* in the `+{root}+/collections/+{collectionId}+/items` GET response.

<<moving-feature-properties-table>> defines the set of properties that may be used to describe a moving feature.
The schema for the moving feature object presented in this clause is an extension of the *_GeoJSON Feature Object_* defined in link:https://datatracker.ietf.org/doc/html/rfc7946#section-3.2[GeoJSON].
By default, the properties defined in <<moving-feature-properties-table>> are the same as the link:https://docs.ogc.org/is/19-045r3/19-045r3.html#mfeature[*_MovingFeature Object_* in OGC MF-JSON].
The semantics of each property are also the same as those defined in MF-JSON.

However, depending on where this schema is used (i.e., depending on which resource produces results with which query parameter), there are differences in requirements from the schema defined in MF-JSON;
as sometimes it only needs to have static information, and sometimes it also has a *temporalGeometry*.
For example, in MF-JSON, `type` and `temporalGeometry` are mandatory, but in this API, `id` and `type` are mandatory. This is why the defined schema is represented in GeoJSON, not MF-JSON.

[[moving-feature-properties-table]]
[reftext='{table-caption} {counter:table-num}']
.Table of the properties related to the moving feature
[cols="25,10,65",options="header"]
|===
|Property       |Requirement    |Description
|_id_           |M |A unique identifier to the moving feature.
|_type_         |M |The GeoJSON feature type (i.e., one of 'Feature' or 'FeatureCollection').
|_geometry_     |O |Projective geometry of the moving feature.
|_properties_   |O |A set of properties of GeoJSON.
|_bbox_         |O |Bounding box information for the moving feature.
|*time*         |O |Life span information for the moving feature.
|*crs*          |O |Coordinate reference system (CRS) information for the moving feature.
|*trs*          |O |Temporal reference system information for the moving feature.
|<<resource-temporalGeometrySequence-section,*temporalGeometry*>> |O |A sequence of <<resource-temporalPrimitiveGeometry-section,*TemporalPrimitiveGeometry*>> for the moving feature.
|<<resource-temporalProperties-section,*temporalProperties*>> |O |A set of <<resource-temporalProperty-section,*TemporalProperty*>> of the moving feature.
|===

NOTE: The properties _id_, _type_, _geometry_, _properties_, and _bbox_ were inherited from link:https://datatracker.ietf.org/doc/html/rfc7946#section-3.2[GeoJSON].

NOTE: The properties *time*, *crs*, *trs*, *temporalGeometry*, and *temporalProperties* were inherited from link:https://docs.ogc.org/is/19-045r3/19-045r3.html#mfeature[OGC MF-JSON]

include::requirements/movingfeature/movingfeature/REQ_mandatory-movingfeature.adoc[]

==== Operation
//TODO: Why Replace operation is not supported
===== Retrieve
The retrieve operation is defined in the `Feature` conformance class of OGC API — Features.
No modifications are needed to support <<resource-movingfeature-section,*MovingFeature*>> resources.

. Issue a `GET` request on the `+{root}+/collections/+{collectionId}+/items/+{mFeatureId}+` path

[[movingfeature-identifier]]
The `+{mFeatureId}+` path parameter is the unique identifier for a single moving feature offered by the API.
The list of valid values for `+{mFeatureId}+` is provided in the <<resource-movingfeatures-section,`+{root}+/collections/+{collectionId}+/items`>> GET response.

Support for GET on the `+{root}+/collections/+{collectionID}+/items/+{mFeatureId}+` path is required by OGC API — Features.

include::requirements/movingfeature/movingfeature/REQ_operation-movingfeature-get.adoc[]

===== Delete
The delete operation is defined in the `link:http://docs.ogc.org/DRAFTS/20-002.html#delete[DELETE]` conformance class of OGC API — Features.

. Issue a `DELETE` request on `+{root}+/collections/+{collectionId}+/items/+{mFeatureId}+` path

Support for the HTTP DELETE method is required by OGC API — Features.

include::requirements/movingfeature/movingfeature/REQ_operation-movingfeature-delete.adoc[]

==== Response
===== Retrieve
A successful response to the *MovingFeature* GET operation is a set of metadata that describes the moving feature identified by the <<movingfeature-identifier,`+{mFeatureId}+`>> parameter.
This response does not include a set of temporal object information.
The temporal object information may be accessed using  <<resource-temporalGeometrySequence-section,*TemporalGeometry*>> and <<resource-temporalProperties-section,*TemporalProperties*>> operations.

include::requirements/movingfeature/movingfeature/REQ_response-movingfeature-get.adoc[]

[#movingfeature-schema,reftext='MovingFeature GET Response Schema']
.MovingFeature GET Response Schema (movingFeature.yaml):
[source,yaml]
----
include::../openapi/schemas/movingFeature.yaml[]
----

The `time` property of the *MovingFeature* response represents a particular period of moving feature existence.
// TODO: Add note using MF-JSON MovingFeature object

The following JSON payload is an example of a response to an OGC API — Moving Features *MovingFeature* operation.
[#movingfeature-example,reftext=`MovingFeature Example`]
.An Example of a MovingFeature JSON Payload:
[source,json]
----
include::../openapi/examples/movingFeature.json[]
----

===== Delete
A successful response to the *Collection* DELETE operation is an HTTP status code.

include::requirements/movingfeature/movingfeature/REQ_response-movingfeature-delete.adoc[]

==== Error situations
The requirements for handling unsuccessful requests are provided in the <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.
