[[clause-core-collection]]
== Requirements Class "Moving Feature Collection Catalog"
=== Overview

include::requirements/collection_catalog/requirements_class_collection.adoc[]

The `Moving Feature Collection Catalog` requirements class defines the requirements for a moving feature collection.
A moving feature collection is an object that provides information about and access to a set of related <<clause-core-movingfeature,Moving Features>>.

=== Information Resources
The two resources defined in this Requirements Class are summarized in <<collection-resources>>.

[[collection-resources]]
.Moving Feature Collection Catalog Resources
[width="90%",cols=",,,",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
.2+|<<resource-collections-section,*Collections*>>
.2+|`{root}/collections`
^|GET |Get information which describes the set of available collections from the *Collections* resource
^|POST|Add a new resource (<<resource-collection-section,Collection>>) instance to a *Collections* resource

.3+|<<resource-collection-section,*Collection*>>
.3+|`{root}/collections/{collectionId}`
^|GET   |Get information about a specific *Collection* resource ({collectionId}) of geospatial data
^|PUT   |Update information about a specific *Collection* resource ({collectionId})
^|DELETE|Delete a specific *Collection* resource ({collectionId})
|===

include::clause_8_requirements_resource_collections.adoc[]

include::clause_8_requirements_resource_collection.adoc[]