
[[clause-core-collection]]
== Requirements Class "Collection Catalog"
=== Overview
include::requirements/collection/requirements_class_movingfeature_collection.adoc[]

The `Collection Catalog` requirements class defines the requirements for a collection.
A collection is an object that provides information about and access to a set of related <<clause-core-movingfeature,MovingFeature>>.

=== Information Resources
The two resources defined in this Requirements Class are summarized in <<collection-resources>>.

[#collection-resources,reftext='{table-caption} {counter:table-num}']
.Collection Catalog Resources
[width="90%",cols="10,10,5,20",options="header"]
|===
^|Resource ^|URI ^|HTTP Method ^|Description
|<<resource-collections-section,Collections>> |`{root}/collections` ^|GET |Information which describes the set of available Collections
|<<resource-collection-section,Collection>> |`{root}/collections/{collectionId}` ^|GET |Information about a specific collection of geospatial data with links to distribution
|===


[[resource-collections-section]]
=== Resource Collections
The `Collections` operation returns a set of metadata which describes the collections available from this API.
The catalog of collections returned to the response can be limited using the <<bbox-section,bbox>>, <<datetime-section,datetime>>, and <<limit-section,limit>> parameters.

==== Parameters
The query parameters http://docs.opengeospatial.org/DRAFTS/20-024.html#bbox-parameter-requirements[`bbox`], http://docs.opengeospatial.org/DRAFTS/20-024.html#datetime-parameter-requirements[`datetime`] and http://docs.opengeospatial.org/DRAFTS/20-024.html#limit-parameter-requirements[`limit`] are inherited from API - Common.
All requirements and recommendations in API - Common regarding these parameters also apply for API - MovingFeatures.

[[bbox-section]]
===== Parameter bbox
include::requirements/parameter/REQ_parameter-bbox.adoc[]

[[datetime-section]]
===== Parameter datetime
include::requirements/parameter/REQ_parameter-datetime.adoc[]

[[limit-section]]
===== Parameter limit
include::requirements/parameter/REQ_parameter-limit.adoc[]

==== Operation
This operation is defined in the `Collections` conformance class of API-Common.
No modifications are needed to support `MovingFeature` resources.

. Issue a `GET` request on `{root}/collections` path

Support for GET on the `{root}/collections` path is required by API-Common.

include::requirements/collection/REQ_operation-collections.adoc[]

==== Response
A successful response to the `Collections` operation is a document that contains summary metadata for each collection accessible through the API.
In a typical API deployment, the `Collections` Response will list collections of all offered resource types.
The collections where the value of the `itemType` property is `movingfeature` are collections of moving features.

include::requirements/collection/REQ_response-collections.adoc[]

[#collections-schema,reftext='Collections Response Schema']
.Collections Response Schema
[source,yaml]
----
include::schema/collections.yaml[]
----

The following JSON payload is an example of a response to an OGC API-MovingFeatures `Collections` operation.
[#collections-example,reftext=`Collections Example`]
.Collections Example
[source,json]
----
include::examples/collections.json[]
----

==== Error situations
The requirements for handling unsuccessful requests are provided in <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.


[[resource-collection-section]]
=== Resource Collection
A Collection information object is the set of metadata that describes a single collection.
An abbreviated copy of this information is returned for each `Collection` in the `{root}/collections` response.

[[collection-schema]]
The schema for the collection information object presented in this clause is an extension of the collection schema defined in http://docs.opengeospatial.org/DRAFTS/20-024.html#collection-description[OGC API-Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API-Features].

<<collection-properties-table>> defines the set of properties that may be used to describe a collection.

[#collection-properties-table,reftext='{table-caption} {counter:table-num}']
.Table of collection properties
[cols="30,5,65",options="header"]
|===
|Property           |Requirement |Description
|_**id**_           |M |A unique identifier to the collection.
|_**title**_        |O |A human-readable name given to the collection.
|_**description**_  |O |A free-text description of the collection.
|_**links**_        |M |A list of links for navigating the API (e.g. link to previous or next pages; links to alternative representations, etc.)
|_**extent**_       |O |The spatio-temporal coverage of the collection.
|_**itemType**_     |M |Fixed to the value "movingfeature".
|updateFrequency    |M |A time interval of sampling location. The time unit of this property is second.
|===

NOTE: The properties _id_, _title_, _description_, _links_, _extent_, and _itemsType_ were inherited from http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API-Common] and http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#\_collection\_[OGC API-Features].

NOTE: An update frequency is one of the most important properties of moving feature collection.
It is determined by a data source. It can use to determine the continuity of the moving feature's trajectory.

include::requirements/collection/REQ_mandatory-collection.adoc[]

==== Operation
This operation is defined in the `Collection` conformance class of API-Common.
No modifications are required to support `MovingFeature` resources.

. Issue a `GET` request on the `{root}/collections/{collectionId}` path

[[collection-identifier]]
The {collectionId} parameter is the unique identifier for a single collection offered by the API.
The list of valid values for `{collectionId}` is provided in the <<resource-collections-section,`/collections`>> response.

Support for the `{root}/collections/{collectionId}` path is required by OGC API-Common.

include::requirements/collection/REQ_operation-collection.adoc[]

==== Response
A successful response to the `Collection` operation is a set of metadata that describes the collection identified by the <<collection-identifier,`{collectionId}`>> parameter.

include::requirements/collection/REQ_response-collection.adoc[]

[#collection-info-schema,reftext='Collection Response Schema']
.Collection Response Schema
[source,yaml]
----
include::schema/collectionInfo.yaml[]
----

The following JSON payload is an example of a response to an OGC API-MovingFeatures `Collection` operation.
[#collection-info-example,reftext=`Collection Information Example`]
.Collection Information Example
[source,json]
----
include::examples/collection.json[]
----

==== Error situations
The requirements for handling unsuccessful requests are provided in <<http-response>>.
General guidance on HTTP status codes and how they should be handled is provided in <<http-status-codes>>.