////
[[req_mf-tpgeometry-op-delete]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/tpgeometry-delete*
^|A |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `DELETE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation_3[`/req/create-replace-delete/delete/delete-op`].
^|B |For every temporal geometry in a moving feature (path `+{root}+/collections/+{collectionId}+/items/+{mFeatureId}+`), the server SHALL support the HTTP DELETE operation at the path `+{root}+/collections/+{collectionId}+/items/+{mFeatureId}+/tgsequence/+{tGeometryId}+`
^|C |The path parameter `collectionId` is each `id` property in the *Collection* GET operation response where the value of the `itemType` property is specified as *MovingFeature*. +
The path parameter `mFeatureId` is an `id` property of the moving feature. The path parameter `tGeometryId` is an `id` property of the temporal geometry.
|===
////

[[req_mf-tpgeometry-op-delete]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/tpgeometry-delete
part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `DELETE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation_3[`/req/create-replace-delete/delete/delete-op`].
part:: For every temporal geometry in a moving feature (path `{root}/collections/{collectionId}/items/{mFeatureId}`), the server SHALL support the HTTP DELETE operation at the path `{root}/collections/{collectionId}/items/{mFeatureId}/tgsequence/{tGeometryId}`
part:: The path parameter `collectionId` is each `id` property in the *Collection* GET operation response where the value of the `itemType` property is specified as *movingfeature*. +
The path parameter `mFeatureId` is an `id` property of the moving feature. +
The path parameter `tGeometryId` is an `id` property of the temporal geometry.
====