////
[[req_mf-tproperty-op-post]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/tproperty-post*
^|A |An implementation of the OGC API — MF SHALL comply with the OGC API — Features `CREATE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/insert-post-op`].
^|B |An implementation of the OGC API — MF SHALL comply with the OGC API — Features `CREATE` request body requirements link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/insert-body` and `/req/create-replace-delete/insert-content-type`].
^|C |The content of the request body SHALL be based upon the <<tvalue-schema,TemporalPrimitiveValue>> schema.
^|D |The ending date-time instance (*_t_end_*) in the temporal value object in <<resource-temporalProperty-section,*TemporalProperty*>>, determined by `tPropertyName`, SHALL be earlier than the beginning date-time instance (*_t_new_*) in the temporal value object in the request body, i.e., *_t_end < t_new_*.
|===
////

[[req_mf-tproperty-op-post]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/tproperty-post
part:: An implementation of the OGC API — MF SHALL comply with the OGC API — Features `CREATE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/insert-post-op`].
part:: An implementation of the OGC API — MF SHALL comply with the OGC API — Features `CREATE` request body requirements link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/insert-body` and `/req/create-replace-delete/insert-content-type`].
part:: The content of the request body SHALL be based upon the <<tvalue-schema,TemporalPrimitiveValue>> schema.
part:: The ending date-time instance (*_t_end_*) in the temporal primitive value object in *TemporalProperty*(<<resource-temporalProperty-section>>), determined by `tPropertyName`, SHALL be earlier than the beginning date-time instance (*_t_new_*) in the temporal primitive value object in the request body, i.e., *_t_end < t_new_*.
====