////
[[req_core_param-datetime]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/common/param-datetime*
^|A |An implementation instance of the OGC API — Moving Features Standard SHALL support the DateTime (`datetime`) parameter for the operation.
^|B |Requests which include the DateTime parameter SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#datetime-parameter-requirements[`/req/collections/rc-time-definition`].
^|C |Responses to DateTime requests SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#datetime-parameter-requirements[`/req/collections/rc-time-response`].
|===
////

[[req_core_param-datetime]]
[requirement]
====
[%metadata]
identifier:: /req/common/param-datetime
part:: An implementation instance of the OGC API — Moving Features Standard SHALL support the DateTime (`datetime`) parameter for the operation.
part:: Requests which include the DateTime parameter SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#datetime-parameter-requirements[`/req/collections/rc-time-definition`].
part:: Responses to DateTime requests SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#datetime-parameter-requirements[`/req/collections/rc-time-response`].
====