////
[[req_core_param-bbox]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/common/param-bbox*
^|A |An implementation instance of the OGC API — Moving Features Standard SHALL support the Bounding Box (`bbox`) parameter for the operation.
^|B |Requests which include the Bounding Box parameter SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#bbox-parameter-requirements[`/req/collections/rc-bbox-definition`].
^|C |Responses to Bounding Box requests SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#bbox-parameter-requirements[`/req/collections/rc-bbox-response`].
|===
////

[[req_core_param-bbox]]
[requirement]
====
[%metadata]
identifier:: /req/common/param-bbox
// part:: An implementation instance of the OGC API — Moving Features Standard SHALL support the Bounding Box (`bbox`) parameter for the operation.
// part:: Requests which include the Bounding Box parameter SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#bbox-parameter-requirements[`/req/collections/rc-bbox-definition`].
// part:: Responses to Bounding Box requests SHALL comply with OGC API — Common requirement link:https://docs.ogc.org/DRAFTS/20-024.html#bbox-parameter-requirements[`/req/collections/rc-bbox-response`].
[.component,class=part]
--
The `bbox` parameter SHALL possess the following characteristics (using an OpenAPI Specification 3.0 fragment): +
[source,yaml]
----
name: bbox
in: query
required: false
schema:
  type: array
  oneOf:
    - minItems: 4
      maxItems: 4
    - minItems: 6
      maxItems: 6
  items:
    type: number
style: form
explode: false
----
--
[.component,class=part]
--
The bounding box SHALL be provided as four or six numbers, depending on whether the coordinate reference system includes a vertical axis (height or depth): +

* Lower left corner, coordinate axis 1
* Lower left corner, coordinate axis 2
* Minimum value, coordinate axis 3 (optional)
* Upper right corner, coordinate axis 1
* Upper right corner, coordinate axis 2
* Maximum value, coordinate axis 3 (optional)
--
[.component,class=part]
--
If the bounding box consists of four numbers, the coordinate reference system of the values SHALL be interpreted as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter `bbox-crs`.
--
[.component,class=part]
--
If the bounding box consists of six numbers, the coordinate reference system of the values SHALL be interpreted as WGS 84 longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h) unless a different coordinate reference system is specified in a parameter `bbox-crs`.
--
[.component,class=part]
--
Only features that have a spatial geometry that intersects the bounding box SHALL be part of the result set, if the `bbox` parameter is provided.
--
[.component,class=part]
--
If a feature has multiple spatial geometry properties, it is the decision of the server whether only a single spatial geometry property is used to determine the extent or all relevant geometries.
--
[.component,class=part]
--
The `bbox` parameter SHALL match all features in the collection that are not associated with a spatial geometry, too.
--
[.component,class=part]
--
The coordinate values SHALL be within the extent specified for the coordinate reference system.
--
====