////
[[req_mf_mf-op-delete]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/mf-delete*
^|A |An implementation of the OGC API — MF SHALL comply with the OGC API — Feature `DELETE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation_3[`req/create-replace-delete/delete/delete-op`].
^|B |For every moving feature in a moving feature collection (path `{root}/collections/{collectionId}`), the server SHALL support the HTTP DELETE operation at the path `{root}/collections/{collectionId}/items/{mFeatureId}`
^|C |The path parameter `collectionId` is each `id` property in the *Collection* GET operation response where the value of the `itemType` property is specified as *MovingFeature*. The path parameter `mFeatureId` is an `id` property of the moving feature.
|===
////

[[req_mf_mf-op-delete]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/mf-delete
part:: An implementation of the OGC API — MF SHALL comply with the OGC API — Feature `DELETE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation_3[`req/create-replace-delete/delete/delete-op`].
part:: For every moving feature in a moving feature collection (path `{root}/collections/{collectionId}`), the server SHALL support the HTTP DELETE operation at the path `{root}/collections/{collectionId}/items/{mFeatureId}`
part:: The path parameter `collectionId` is each `id` property in the *Collection* GET operation response where the value of the `itemType` property is specified as *MovingFeature*. The path parameter `mFeatureId` is an `id` property of the moving feature.
====
