////
[[req_mf-response-delete]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/mf-delete-success*
^|A |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `DELETE` response requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_response_3[`/req/create-replace-delete/delete-response`].
^|B |If no resource with the identifier exists in the collection, the server SHALL respond with a not-found exception (`404`).
|===
////

[[req_mf-response-delete]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/mf-delete-success
// part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `DELETE` response requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_response_3[`/req/create-replace-delete/delete-response`].
part:: A successful execution of the operation SHALL be reported as a response with an HTTP status code `200` or `204`.
part:: If the operation is not executed immediately, but is added to a processing queue, the response SHALL have an HTTP status code `202`.
part:: If no resource with the identifier exists in the collection, the server SHALL respond with a not-found exception (`404`).
====