////
[[req_mf_subtemporalvalue-parameter-response]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/param-subtemporalvalue-response*
^|A | The endpoint SHALL return only a subsequence of the temporal primitive values derived from temporal property for a specified time interval (new start time and new end time) included in the `datetime` parameter, using interpolated temporal property values according to the `interpolation` property in <<resource-temporalProperty-section,*TemporalProperty*>>, if the `subTemporalValue` parameter is "ture".
^|B | If the `subTemporalValue` parameter is "true", the `datetime` parameter SHALL match all temporal property objects in the moving feature.
^|C | If the `subTemporalValue` parameter is "true", the `interpolation` property in the response SHALL be the same as the temporal property's `interpolation` property value.
^|D | The `subTemporalValue` parameter SHALL not be used with the <<leaf-section,`leaf`>> parameter.
|===
////

[[req_mf_subtemporalvalue-parameter-response]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/param-subtemporalvalue-response
part:: The endpoint SHALL return only a subset of the temporal primitive values derived from the temporal property for a specified time interval (new start time and new end time) included in the `datetime` parameter, using interpolated temporal property values according to the `interpolation` property in *TemporalProperty*(<<resource-temporalProperty-section>>), if the `subTemporalValue` parameter is "ture".
part:: If the `subTemporalValue` parameter is "true", the `datetime` parameter SHALL match all temporal property objects in the moving feature.
part:: If the `subTemporalValue` parameter is "true", the `interpolation` property in the response SHALL be the same as the temporal property's `interpolation` property value.
part:: The `subTemporalValue` parameter SHALL not be used with the `leaf`(<<leaf-section>>) parameter.
====