////
[[req_mf_subtemporalvalue-parameter-definition]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/param-subtemporalvalue-definition*
^|A |The operation SHALL support a query parameter `subTemporalValue` with the following characteristics (using an OpenAPI Specification 3.0 fragment): +
[source,yaml]
----
include::../../../openapi/parameters/subtemporalvalue.yaml[]
----
^|B |The `subTemporalValue` parameter SHALL be used with `datetime` parameter.
^|C |If the `subTemporalValue` parameter is "true", the `datetime` parameter SHALL be a bounded interval, not half-bounded intervals or a date-time.
|===
////

[[req_mf_subtemporalvalue-parameter-definition]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/param-subtemporalvalue-definition

[.component,class=part]
--
The operation SHALL support a query parameter `subTemporalValue` with the following characteristics (using an OpenAPI Specification 3.0 fragment):

[source,yaml]
----
include::../../../openapi/parameters/subtemporalvalue.yaml[]
----
--

[.component,class=part]
--
The `subTemporalValue` parameter SHALL be used with `datetime` parameter.
--

[.component,class=part]
--
If the `subTemporalValue` parameter is "true", the `datetime` parameter SHALL be a bounded interval, not half-bounded intervals or a date-time.
--
====