[[conf_mfc_collections_get_success]]
////
[cols=">20h,<80d",width="100%"]
|===
|*Abstract Test {counter:conf-id}* |*/conf/mf-collection/collections-get-success*
|Requirement    | <<req_mfc-collections-response-get, /req/mf-collection/collections-get-success>>
|Test purpose   | Validate that the *MovingFeature Collections* complies with the required structure and contents.
|Test method    |
1. Validate that all response documents comply with OGC API — Common link:http://docs.ogc.org/DRAFTS/20-024.html#_collections_rootcollections_tests[/conf/collections/rc-md-success] +
2. Validate the *Collections* resource for all supported media types using the resources and tests identified in <<collections-metadata-schema>> +
3. Verify that the response document contains a `itemType` property and its value is 'movingfeature'
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/mf-collection/collections-get-success
target:: /req/mf-collection/collections-get-success
test-purpose:: Validate that the *MovingFeature Collections* complies with the required structure and contents.
test-method::
+
--
1. Validate that all response documents comply with OGC API — Common link:http://docs.ogc.org/DRAFTS/20-024.html#_collections_rootcollections_tests[/conf/collections/rc-md-success] +
2. Validate the *Collections* resource for all supported media types using the resources and tests identified in <<collections-metadata-schema>> +
3. Verify that the response document contains a `itemType` property and its value is 'movingfeature'
--
====

The *Collections* content may be retrieved in a number of different formats. The following table identifies the applicable schema document for each format and the test to be used to validate the against that schema. All supported formats should be exercised.

[[collections-metadata-schema]]
.Schema and Tests for MovingFeature Collections content
[width="90%",cols="3",options="header"]
|===
|Format |Schema Document |Test ID
|HTML |<<collections-schema, collections.yaml>>|link:https://docs.ogc.org/is/19-072/19-072.html#ats_html_content[/conf/html/content]
|JSON |<<collections-schema, collections.yaml>>|link:https://docs.ogc.org/is/19-072/19-072.html#ats_json_content[/conf/json/content]
|===