[[conf_mfc_collection_delete]]
////
[cols=">20h,<80d",width="100%"]
|===
|*Abstract Test {counter:conf-id}* |*/conf/mf-collection/collection-delete*
|Requirement    |
<<req_mfc-collection-op-delete, /req/mf-collection/collection-delete>> +
<<req_mfc-collection-response-delete, /req/mf-collection/collection-delete-success>>
|Test purpose   | Validate that the *MovingFeature Collection* can be deleted at the expected location.
|Test method    |
1. Validate that the server complies with OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_operation_3[DELETE operation requirements] +
2. Issue an HTTP DELETE request to the URL `+{root}+/collections/+{collectionId}+` +
3. Validate the contents of the response using test <<conf_mfc_collection_delete_success, `/conf/mf-collection/collections-put-success`>>
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/mf-collection/collection-delete
target:: /req/mf-collection/collection-delete
target:: /req/mf-collection/collection-delete-success
test-purpose:: Validate that the *MovingFeature Collection* can be deleted at the expected location.
test-method::
+
--
1. Validate that the server complies with OGC API — Features - Part 4 link:http://docs.ogc.org/DRAFTS/20-002.html#_operation_3[DELETE operation requirements] +
2. Issue an HTTP DELETE request to the URL `{root}/collections/{collectionId}` +
3. Validate the contents of the response using <<conf_mfc_collection_delete_success>>
--
====