////
[[req_mfc-collections-op-post]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/mf-collection/collections-post*
^|A |An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `CREATE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/insert-post-op`].
^|B |An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `CREATE` request body requirements link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/insert-body` and `/req/create-replace-delete/insert-content-type`].
^|C |The content of the request body SHALL be based upon the <<collection-requestbody-schema, *Collection* request body schema>>.
|===
////

[[req_mfc-collections-op-post]]
[requirement]
====
[%metadata]
identifier:: /req/mf-collection/collections-post
part:: An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `CREATE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/post-op`].
part:: An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `CREATE` request body requirements link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/post-body` and `/req/create-replace-delete/post-content-type`].
part:: The content of the request body SHALL be based upon the <<collection-requestbody-schema, *Collection* request body schema>>.
====