[[conf_mf_tproperty_post]]
////
[cols=">20h,<80d",width="100%"]
|===
|*Abstract Test {counter:conf-id}* |*/conf/movingfeatures/tproperty-post*
|Requirement    |
<<req_mf_mandatory-tproperty, /req/movingfeatures/tproperty-mandatory>> +
<<req_mf-tproperty-op-post, /req/movingfeatures/tproperty-post>> +
<<req_mf-tproperty-response-post, /req/movingfeatures/tproperty-post-success>>
|Test purpose   | Validate that the *TemporalPrimitiveValue* can be created at the expected location.
|Test method    |
1. Validate that the server complies with OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[POST operation requirements] +
2. Validate that a body of a POST request using for all supported media types using the resources and tests identified in <<tproperty-requestbody-schema>> and <<temporalValue-properties-table>> +
3. Validate that the request body complies OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[POST request body requirements] +
4. Issue an HTTP POST request to the URL `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` +
5. Validate the contents of the response using test <<conf_mf_tproperty_post_success, `/conf/movingfeatures/tproperty-post-success`>>
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/movingfeatures/tproperty-post
target:: /req/movingfeatures/tproperty-mandatory
target:: /req/movingfeatures/tproperty-post
target:: /req/movingfeatures/tproperty-post-success
test-purpose:: Validate that the *TemporalPrimitiveValue* can be created at the expected location.
test-method::
+
--
1. Validate that the server complies with OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[POST operation requirements] +
2. Validate that a body of a POST request using for all supported media types using the resources and tests identified in <<tproperty-requestbody-schema>> and <<temporalValue-properties-table>> +
3. Validate that the request body complies OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[POST request body requirements] +
4. Issue an HTTP POST request to the URL `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` +
5. Validate the contents of the response using <<conf_mf_tproperty_post_success>>
--
====

[[tproperty-requestbody-schema]]
.Schema and Tests for Request Body of `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties/{tPropertyName}` POST
[width="90%",cols="3",options="header"]
|===
|Format  |Schema Document |Test ID
|HTML |<<tvalue-schema, tvalue_requestbody.yaml>>|link:https://docs.ogc.org/is/19-072/19-072.html#ats_html_content[/conf/html/content]
|JSON |<<tvalue-schema, tvalue_requestbody.yaml>>|link:https://docs.ogc.org/is/19-072/19-072.html#ats_json_content[/conf/json/content]
|===