////
[[req_mfc-collection-op-put]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/mf-collection/collection-put*
^|A |An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `PUT` operation requirement http://docs.ogc.org/DRAFTS/20-002.html#_operation_2[`/req/create-replace-delete/update-put-op`].
^|B |An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `PUT` request body requirements http://docs.ogc.org/DRAFTS/20-002.html#_request_body_2[`/req/create-replace-delete/update-put-body` and `/req/create-replace-delete/update-put-content-type`].
^|C |The content of the request body SHALL be based upon the <<collection-requestbody-schema, *Collection* request body schema>>, except `updateFrequency`. +
If the `updateFrequency` is included in the request body, the server SHALL ignore it.
|===
////

[[req_mfc-collection-op-put]]
[requirement]
====
[%metadata]
identifier:: /req/mf-collection/collection-put
part:: An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `PUT` operation requirement http://docs.ogc.org/DRAFTS/20-002.html#_operation_2[`/req/create-replace-delete/put-op`].
part:: An implementation of the OGC API - Moving Features Standard SHALL comply with the OGC API — Features `PUT` request body requirements http://docs.ogc.org/DRAFTS/20-002.html#_request_body_2[`/req/create-replace-delete/put-body` and `/req/create-replace-delete/put-content-type`].
part:: The content of the request body SHALL be based upon the <<collection-requestbody-schema, *Collection* request body schema>>, except `updateFrequency`. +
If the `updateFrequency` is included in the request body, the server SHALL ignore it.
====
