////
[[req_mf-features-op-post]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/features-post*
^|A |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` operation requirement http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/insert-post-op`].
^|B |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` request body requirements http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/insert-body` and `/req/create-replace-delete/insert-content-type`].
^|C |The content of the request body SHALL be based upon the link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#mfeature[*_MovingFeature_* object] and https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#mfeaturecollection[*_MovingFeatureCollection_* object] in <<OGC-MF-JSON,OGC Moving Features JSON Encoding Standard>>.
|===
////

[[req_mf-features-op-post]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/features-post
// part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` operation requirement http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/post-op`].
// part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` request body requirements http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/post-body` and `/req/create-replace-delete/post-content-type`].
part:: The server SHALL support the HTTP POST operation at the resource endpoint(`{root}/collections/{collectionId}/items`).
part:: A `Content-Type` header SHALL be used to declare the media type of the request body containing a representation of the resource to be added.
part:: The content of the request body SHALL be based upon the link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#mfeature[*_MovingFeature_* object] and https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#mfeaturecollection[*_MovingFeatureCollection_* object] in <<OGC_19-045r3,OGC Moving Features JSON Encoding Standard>>.
====

[NOTE]
See link:https://www.rfc-editor.org/rfc/rfc9110#field.content-type[section 8.3 of RFC 9110] for details of `Content-Type`.