////
[[req_mf-features-response-post]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/features-post-success*
^|A |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` response requirement http://docs.ogc.org/DRAFTS/20-002.html#_response[`/req/create-replace-delete/insert-response` and `/req/create-replace-delete/insert-response-rid`].
|===
////

[[req_mf-features-response-post]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/features-post-success
part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` response requirement http://docs.ogc.org/DRAFTS/20-002.html#_response[`/req/create-replace-delete/post-response` and `/req/create-replace-delete/post-response-rid`].
part:: If the body of a POST request contains a collection of the resource, a response with HTTP status code `201` SHALL include a `Locations` header with the list of the URIs of the newly added resources.
part:: The elements in the `Locations` header SHALL be in the same order and size as the collection of resources contained in the body of the POST request.
====