////
[[req_mf-tgsequence-response-post]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/tgsequence-post-success*
^|A |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` response requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_response[`/req/create-replace-delete/insert-response` and `/req/create-replace-delete/insert-response-rid`].
|===
////

[[req_mf-tgsequence-response-post]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/tgsequence-post-success
// part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` response requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_response[`/req/create-replace-delete/post-response` and `/req/create-replace-delete/post-response-rid`].
part:: If the operation completes successfully, the server SHALL assign a new, unique identifier within the collection for the newly added resource.
part:: A successful execution of the operation SHALL be reported as a response with an HTTP status code `201`.
part:: A response with HTTP status code `201` SHALL include a `Location` header with the URI of the newly added resource (i.e., path of the resource endpoint).
part:: If the operation is not executed immediately, but is added to a processing queue, the response SHALL have an HTTP status code `202`.
====