////
[[req_mf-tproperties-op-post]]
[width="90%",cols="2,6a",options="header"]
|===
^|*Requirement {counter:req-id}* |*/req/movingfeatures/tproperties-post*
^|A |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/insert-post-op`].
^|B |An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` request body requirements link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/insert-body` and `/req/create-replace-delete/insert-content-type`].
^|C |The content of the request body SHALL be based upon a <<tproperty-schema,TemporalProperty>> defined in this API or a link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#pvalues[ParametricValues object] defined in <<OGC-MF-JSON,OGC Moving Features JSON Encoding Standard>>.
|===
////

[[req_mf-tproperties-op-post]]
[requirement]
====
[%metadata]
identifier:: /req/movingfeatures/tproperties-post
part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` operation requirement link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[`/req/create-replace-delete/insert-post-op`].
part:: An implementation of the OGC API — Moving Features Standard SHALL comply with the OGC API — Features `CREATE` request body requirements link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[`/req/create-replace-delete/insert-body` and `/req/create-replace-delete/insert-content-type`].
part:: The content of the request body SHALL be based upon a <<tproperty-schema,TemporalProperty>> defined in this API or a link:https://docs.opengeospatial.org/is/19-045r3/19-045r3.html#pvalues[ParametricValues object] defined in <<OGC_19-045r3,OGC Moving Features JSON Encoding Standard>>.
====