[[conf_mf_tproperties_get]]
////
[cols=">20h,<80d",width="100%"]
|===
|*Abstract Test {counter:conf-id}* |*/conf/movingfeatures/tproperties-get*
|Requirement    |
<<req_mf-tproperties-op-get, /req/movingfeatures/tproperties-get>> +
<<req_mf-tproperties-response-get, /req/movingfeatures/tproperties-get-success>>
|Test purpose   | Validate that the *TemporalProperties* can be identified and extracted from a MovingFeature object using query parameters.
|Test method    |
For every *TemporalProperty* identified in *MovingFeature*, issue an HTTP GET request to the URL `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` where `{collectionId}` is the id property for a *MovingFeature Collection* described in the *MovingFeature Collection* content and `{mFeatureId}` is the id property for the *MovingFeature*

1. Validate that a document was returned with a status code `200` +
2. Validate the contents of the returned document using test <<conf_mf_tproperties_get_success, `/conf/movingfeatures/tproperties-get-success`>>

Repeat these tests using the following parameter tests that are defined in the OGC API — Common: +
- Limit: link:http://docs.ogc.org/DRAFTS/20-024.html#_limit_tests[Limit Tests] +
- Date-Time: link:http://docs.ogc.org/DRAFTS/20-024.html#_date_time_tests[Date-Time Tests]

Execute requests with combinations of the `"datetime"` query parameters and verify that only features are returned that match both selection criteria.
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/movingfeatures/tproperties-get
target:: /req/movingfeatures/tproperties-get
target:: /req/movingfeatures/tproperties-get-success
target:: /req/common/param-limit
target:: /req/common/param-datetime
test-purpose:: Validate that the *TemporalProperties* can be identified and extracted from a MovingFeature object using query parameters.
test-method::
+
--
For every *TemporalProperty* identified in *MovingFeature*, issue an HTTP GET request to the URL `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` where `{collectionId}` is the id property for a *MovingFeature Collection* described in the *MovingFeature Collection* content and `{mFeatureId}` is the id property for the *MovingFeature*

1. Validate that a document was returned with a status code `200` +
2. Validate the contents of the returned document using <<conf_mf_tproperties_get_success>>

Repeat these tests using the following parameter tests that are defined in the OGC API — Common and OGC API — MF: +
- Limit: link:http://docs.ogc.org/DRAFTS/20-024.html#_limit_tests[Limit Tests] +
- Date-Time: link:http://docs.ogc.org/DRAFTS/20-024.html#_date_time_tests[Date-Time Tests] +
- SubTemporalValue: <<conf_mf_feature_param_subtemporalvalue_definition,SubTemporalValue Definition Test>> and <<conf_mf_feature_param_subtemporalvalue_response,SubTemporalValue Response Test>>

Execute requests with combinations of the `"datetime"` and `"subTemporalValue"` query parameters and verify that only features are returned that match both selection criteria.
--
====