[[conf_mf_tproperties_post]]
////
[cols=">20h,<80d",width="100%"]
|===
|*Abstract Test {counter:conf-id}* |*/conf/movingfeatures/tproperties-post*
|Requirement    |
<<req_mf_mandatory-tproperty, /req/movingfeatures/tproperty-mandatory>> +
<<req_mf-tproperties-op-post, /req/movingfeatures/tproperties-post>> +
<<req_mf-tproperties-response-post, /req/movingfeatures/tproperties-post-success>>
|Test purpose   | Validate that the *TemporalProperty* can be created at the expected location.
|Test method    |
1. Validate that the server complies with OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[POST operation requirements] +
2. Validate that a body of a POST request using for all supported media types using the resources and tests identified in <<tproperties-requestbody-schema>> and <<temporalProperty-properties-table>> +
3. Validate that the request body complies OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[POST request body requirements] +
4. Issue an HTTP POST request to the URL `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` +
5. Validate the contents of the response using test <<conf_mf_tproperties_post_success, `/conf/movingfeatures/tproperties-post-success`>>
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/movingfeatures/tproperties-post
target:: /req/movingfeatures/tproperty-mandatory
target:: /req/movingfeatures/tproperties-post
target:: /req/movingfeatures/tproperties-post-success
test-purpose:: Validate that the *TemporalProperty* can be created at the expected location.
test-method::
+
--
1. Validate that the server complies with OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_operation[POST operation requirements] +
2. Validate that a body of a POST request using for all supported media types using the resources and tests identified in <<tproperties-requestbody-schema>> and <<temporalProperty-properties-table>> +
3. Validate that the request body complies OGC API — Features link:http://docs.ogc.org/DRAFTS/20-002.html#_request_body[POST request body requirements] +
4. Issue an HTTP POST request to the URL `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` +
5. Validate the contents of the response using test <<conf_mf_tproperties_post_success, `/conf/movingfeatures/tproperties-post-success`>>
--
====

[[tproperties-requestbody-schema]]
[reftext='{table-caption} {counter:table-num}']
.Schema and Tests for Request Body of `{root}/collections/{collectionId}/items/{mFeatureId}/tproperties` POST
[width="90%",cols="3",options="header"]
|===
|Format  |Schema Document |Test ID
|HTML |<<tproperty-schema, tproperty_requestbody.yaml>>|link:https://docs.ogc.org/is/19-072/19-072.html#ats_html_content[/conf/html/content]
|JSON |<<tproperty-schema, tproperty_requestbody.yaml>>|link:https://docs.ogc.org/is/19-072/19-072.html#ats_json_content[/conf/json/content]
|JSON |link:https://schemas.opengis.net/movingfeatures/1.0/MF-JSON_Prism.schema.json[MF-JSON_Prism.schema.json]|link:https://docs.ogc.org/is/19-072/19-072.html#ats_json_content[/conf/json/content]
|===